### PR TITLE
WFLY-16794 Missing documentation for SmallRye Fault Tolerance capability

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-16794

### CODE REVIEW

**Comment by rhusar** [comment]
@yersan Are you now the owner of this repo? :)

**Comment by yersan** [comment]
Hello @rhusar , no, I'm not the owner. I have no control over this repo.

**Comment by yersan** [comment]
Looking at the history, @jmesnil or @bstansberry are the ones that can merge PRs here.

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
